[project]
authors = [
    {name = "Qinyu Luo", email = "qinyuluo123@gmail.com"},
]
maintainers = [
    {name = "Arno Edwards", email = "Arno.Edwards@outlook.com"},
]
license = {text = "Apache-2.0"}
requires-python = ">=3.10,<4.0"
dependencies = [
    "loguru>=0.7.2",
    "openai>=1.10.0",
    "gradio>=4.16.0",
    "markdown>=3.5.2",
    "pyyaml>=6.0.1",
    "jedi>=0.19.1",
    "GitPython>=3.1.41",
    "llama-index<0.10.0",
    "chromadb>=0.4.22",
    "prettytable>=3.9.0",
    "python-iso639>=2024.2.7",
    "pydantic-settings>=2.2.1",
    "tomli>=2.0.1",
    "tomli-w>=1.0.0",
]
name = "repoagent"
version = "0.0.6"
description = "An Agent designed to offer an intelligent approach for generating project documentation."
readme = "README.md"

[project.urls]
repository = "https://github.com/LOGIC-10/RepoAgent"

[project.scripts]
repoagent = "repo_agent.main:app"

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.1.14",
]
test = [
    "pytest<8.0.0,>=7.4.4",
    "pytest-mock<4.0.0,>=3.12.0",
]

[tool.pdm.build]
includes = [
    "repo_agent",
]


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pyright]
reportCallIssue="none"